name: Lint, Test, Build

on:
  workflow_dispatch:
    inputs:
      override-packages:
        description: "Override changed packages with this filter (use * to run all packages)"
        required: false
	default: *
        type: string

jobs:
  evaluate-changed-packages:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      packages: ${{ steps.override-filter.outputs.result || steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changed packages
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            foo: 
              - 'src/foo'
             
      - name: Override packages
        id: override-filter
        uses: actions/github-script@v6
        if: ${{ inputs.override-packages }}
        with:
          script: return ["${{ inputs.override-packages }}"]

  lint-test-build:
    needs: evaluate-changed-packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.evaluate-changed-packages.outputs.packages) }}
    if: needs.evaluate-changed-packages.outputs.packages != '[]'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        run: echo ${{ matrix.package }}



